### ISSUE TITLE
Fix, or work around, Safari optimization problems

### ISSUE THREAD

**Issue by tantaman** [vlcn-io/cr-sqlite#246]
Reported by @Azarattum 

https://discord.com/channels/989870439897653248/989870440585494530/1119945592970424500

More context: https://github.com/rhashimoto/wa-sqlite/discussions/94

I can't reproduce this problem with the official SQLite WASM (OSW) build. Given that, my assumption is that is because they do not use asyncify.

Adopting OSW would be a bit problematic given their reliance on shared array buffer.

A better option would be to use the AccessHandlePoolVFS (https://github.com/rhashimoto/wa-sqlite/blob/007f3553564654096403dddc9c54adbf57feadc0/src/examples/AccessHandlePoolVFS.js#L36) assuming this does not break Safari either.

Next steps:
- [ ] Try to repro the problem with AccessHandlePoolVFS
- [ ] If it does not repro, use AccessHandlePoolVFS and coordinate message ports with ServiceWorker if possible, SharedWorker otherwise

Switching to `AccessHandlePoolVFS` will create quite a bit of work for us on the react integration side. Since we will now have to communicate over a message port to a worker, we'll need to find a new way to batch `useQuery` hooks into a single tick of the event loop.

**Comment by Azarattum** [comment]
Shared Workers aren’t supported just for Android, they also don’t work on Safari (<16.0), meaning the wouldn’t work on earlier iOS version and there are a lot of iOS devices that cannot be updated beyond iOS 15. I personally try to target >= iOS 15.4, since this is the oldest iOS version where the most of recent web changes were introduced. Seriously, if you look at the [changelog](https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes) you can almost call this version a “safari update”.

**Comment by rhashimoto** [comment]
AccessHandlePoolVFS relies on the [specification change that made all FileSystemSyncAccessHandle methods synchronous](https://github.com/rhashimoto/wa-sqlite/discussions/67). This reached stable browsers in Chromium 108+, Safari 16.4+, and Firefox 111+.

Although I think you can [share a service across tabs without SharedWorker](https://github.com/rhashimoto/wa-sqlite/discussions/81#discussioncomment-6223838), AccessHandlePoolVFS itself wasn't supported across all major browsers until March 2023 or so.

**Comment by rhashimoto** [comment]
I learned from @quolpr of [another way](https://github.com/rhashimoto/wa-sqlite/issues/35#issuecomment-1178760861), other than Atomics/SharedArrayBuffer, to block a Worker and make an asynchronous call. [importScripts()](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) will block and you can use a service worker to intercept the request for the script file. You can use that to implement a _synchronous_ SQLite VFS with IndexedDB storage (or OPFS if the service worker proxies to another Worker).

It would be slower. It would be ugly. But if you're truly desperate for a solution that doesn't use Asyncify or SharedArrayBuffer or the redefined FileSystemSyncAccessHandle, I think it's out there.

**Comment by tantaman** [comment]
lol that is a very clever but very crazy solution. 🤯

**Comment by rhashimoto** [comment]
I would inject a couple earlier steps to your plan:

* Try a [WebKit Nightly](https://webkit.org/build-archives/) build (for Mac) and hope a fix is already in the pipeline.
* Publish a test page that highlights the problem and file a WebKit bug.

Small sample size, but I've found WebKit to be pretty responsive. I filed two bugs last year and they were fixed in 51 and 1 (!) days.

**Comment by rhashimoto** [comment]
Another relatively easy (since you already build) possible workaround to try is messing with the Emcripten build flags to perturb the generated WASM code in hopes that it won't trigger the runaway recompilation. For example, the [wa-sqlite Makefile uses -Oz](https://github.com/rhashimoto/wa-sqlite/blob/d97375b1b944697ca277cb9d5167344d21d32bfa/Makefile#L46) (and duplicates it [here](https://github.com/rhashimoto/wa-sqlite/blob/d97375b1b944697ca277cb9d5167344d21d32bfa/Makefile#L59), which would be a bug); you could try changing that to -O2 or -O3.

Not using -Oz will make the WASM files quite a bit larger, but IMO that would be preferable to importScripts() if it worked.

**Comment by tantaman** [comment]
Thanks. These are all helpful. I'm tied up improving performance of merges for fly.io's [corrosion](https://community.fly.io/t/reliability-its-not-great/11253) project but will have time to pick this back up end of next week.

**Comment by tantaman** [comment]
@rhashimoto - the -O3 suggestion seems to work.

CPU maxes out at ~280% rather than ~500% and only for a couple of seconds rather than the 30+.

Binary size only changed by a few KB which was surprising.

@Azarattum I'll roll a new release with this change.

**Comment by Azarattum** [comment]
> CPU maxes out at ~300% rather than ~500% and only for a couple of seconds rather than the 30+.

Is this the entire usage or just by "WebKit Threads"?

**Comment by rhashimoto** [comment]
I'm glad you found an easy workaround, and that the trade-offs weren't as costly as I expected (presumably due to Emscripten improvements). I still encourage you to file a WebKit bug when you can in hopes that we won't keep running into it.

**Comment by tantaman** [comment]
@rhashimoto, I think your tip saved me an entire week of work :)

If you or @Azarattum ever want to compare notes on building web apps with SQLite there are a few of us (@schickling, @geoffreylitt) trying to push the boundaries of SQLite on the web.

**Comment by tantaman** [comment]
Be aware @Azarattum that the latest release has some breaking changes in terms of the format of data that comes out of `crsql_changes`.

- values come out in their actual type rather being `quote(value)`
- primary keys are packed into a binary format

I'll do a longer writeup in the announcements.

**Comment by rhashimoto** [comment]
Did the workaround fix iOS, too? And is there a WebKit bug to track?

**Comment by tantaman** [comment]
@rhashimoto - it works on the 2 iPhones and 1 iPad I've tested against.

Haven't filed the webkit issue yet but it is on the todo list for this week.

**Comment by tantaman** [comment]
@quolpr - I only tried O3.
