### ISSUE TITLE
Any way to speed up crsql_changes insertion?

### ISSUE THREAD

**Issue by jeromegn** [vlcn-io/cr-sqlite#252]
I'm testing my project with very large transactions (100K changes). I've noticed, depending on the CPU models and load, that it can take between 4s and 60s to insert 100K changes into `crsql_changes`.

Locally, on a M1 Max, I get the following performance:
- Insert 10K rows in `crsql_changes`: best = 500ms, worst = 900ms
- Insert 100K rows in `crsql_changes`: best = 5s, worst = 9s

I think the "best" here is only because there's no other reads / writes on the DB at the time. This is just a sample of 3 nodes in my cluster in an artificial test.

So these numbers look proportional based on the number of rows.

On my Fly deployment, using shared 1 vCPU instances (~ 1/16th of a server CPU), inserting 100K rows in `crsql_changes` usually takes between 15 and 60s.

This wouldn't be a problem if I could write from multiple threads, but I can't, given the reality of SQLite. I also can't split up the inserts because my thinking is that we want to insert everything related to a single transaction all at once. Is that right or does it not matter because CRDTs and the eventual consistency nature of cr-sqlite? I guess eventual consistency is different than "all changes in a transaction are bundled together".

When I'm applying these large transaction changes, it prevents any other writes to happen in my project. That means anything coming from clients, but also ongoing synchronization round trips as well as gossiped broadcasts.

My current idea to sidestep this issue is to delay applying large transactions at a later time. A "later time" being very close to the current time or else we're slower to become consistent with the rest of the cluster. However, even doing it later is going to "lock" my writes for many seconds.

Let me know if you have any ideas or if you think this might be a bug in cr-sqlite!

**Comment by jeromegn** [comment]
I've gotten a flamegraph during that operation. Maybe that's useful in some way. There's a bunch of other noise,  but nothing as significant as the time spent in crsqlite.

This one took roughly 40s.

(I recommend saving that file and opening it in a browser. Clicking on it has weird fonts and none of the flamegraph functionality it seems.)

![corro2](https://github.com/vlcn-io/cr-sqlite/assets/43325/3564d8c9-ce0c-470c-8f8d-f3919e2ff842)

**Comment by jeromegn** [comment]
Upon summary analysis, it looks like half the time is spent in `sqlite3_prepare_v2`. I think it's a common pattern to cache prepared statements, per connection.

More specifically, I'm thinking a function could do this for us. Statements are known in advance, so calling a function call like `SELECT crsql_cache_prepared_statements()` or something at the beginning of the life of the connection could populate the cache with all / most / many prepared statements and save a lot of time when we have to use these statements.

**Comment by tantaman** [comment]
Haven't had time to read all your commentary yet but on:

> Upon summary analysis, it looks like half the time is spent in sqlite3_prepare_v2. I think it's a common pattern to cache prepared statements, per connection.

> More specifically, I'm thinking a function could do this for us. Statements are known in advance, so calling a function call like SELECT crsql_cache_prepared_statements() or something at the beginning of the life of the connection could populate the cache with all / most / many prepared statements and save a lot of time when we have to use these statements.

We can definitely explore this. We should be able to stick them alongside other statements we're currently caching at extension load time -- https://github.com/vlcn-io/cr-sqlite/blob/dd8c267dd8f79ea380ae53694866123b4cea4352/core/src/ext-data.h#L12-L27

**Comment by jeromegn** [comment]
Looking at it this morning: I noticed all the statements that are taking their sweet time in here can't really be cached because the name of the table is dynamic (`<table_name>__crsql_clock`).

I don't think there's a way around this except by either caching 1 statement per table if we know them in advance or by changing that schema to hold clocks for all tables and index them by a table column.

**Comment by tantaman** [comment]
Caching the statements per table makes sense.

I'll need to fix up how we handle constructing the query, however. Right now the primary key conditions that are filtered by are included directly into the string (after doing some sanitization, and ensuring there's no SQL injection, of course).

E.g.,

```
sqlite3_mprintf("SELECT .. WHERE %s", pk_conditions);
```

That isn't cacheable since it is a different query each time. The cacheable, and safer, route would be to:

1. figure out the type of each primary key value passed to us
2. use the proper sqlite3_bind_x method

(1) means either parsing the string encoding to figure out the type or encoding values in a binary format which includes the type of the thing.

Parsing string encoding:
- `NULL` -> NULL
- `X'[0-9A-Fa-f]+'` -> Blob
- `-?[1-9]{1}[0-9]+` -> Integer
- `-?[0-9]*\.[0-9]*` -> Real
- `'.*'` -> Text (with the caveat that we handle escape sequences `''`

Simpler non reg-ex rules that can quickly determine type:

- Starts with `N` -> Null
- Starts with `X'` -> Blob
- Maybe starts with `-` followed by all digits -> Integer
- Maybe starts with `-` followed by all digits with allowance for one `.` -> Real
- Starts with `'` -> Text

https://www.sqlite.org/datatype3.html

I think I'll start with this string parsing given it doesn't break any existing behavior. Moving to a binary encoding would be optimal, maybe with some special cases to improve dev-x where tables only have a single primary key.

The single primary key case can get a smoother experience since we can omit any special encoding when there is only a single primary key column, making it possible for users to filter crsql_changes by primary key of those tables.

E.g.,

```
SELECT * FROM crsql_changes WHERE pk > ? AND table = ?
```

If there are many primary key columns it seems unavoidable to need to concatenate them together into a single column as we can't union tables with differing numbers of columns.

**Comment by tantaman** [comment]
Relevant PRs so far:

#260 
#259 
#258 
#257 
#256
